name: Mantener Supabase Activo

on:
  schedule:
    - cron: '0 0 */4 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Realizar peticion de prueba a Supabase
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_SECRET_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SECRET_KEY }}"
